# More logical way to require 'dspace-rest-client'
require File.dirname(__FILE__) + '/dspacerestclient'
require File.dirname(__FILE__) + '/dspacerest/auth'
require File.dirname(__FILE__) + '/dspacerest/bitstream'
require File.dirname(__FILE__) + '/dspacerest/collection'
require File.dirname(__FILE__) + '/dspacerest/community'
require File.dirname(__FILE__) + '/dspacerest/item'