# More logical way to require 'dspace-rest-client'
require File.dirname(__FILE__) + '/dspace_client'
require File.dirname(__FILE__) + '/dspacerest/bitstream'
require File.dirname(__FILE__) + '/dspacerest/collection'
require File.dirname(__FILE__) + '/dspacerest/community'
require File.dirname(__FILE__) + '/dspacerest/item'
require File.dirname(__FILE__) + '/dspacerest/metadata'
require File.dirname(__FILE__) + '/dspacerest/repositories/abstract_repository'
require File.dirname(__FILE__) + '/dspacerest/repositories/bitstream_repository'
require File.dirname(__FILE__) + '/dspacerest/repositories/collection_repository'
require File.dirname(__FILE__) + '/dspacerest/repositories/community_repository'
require File.dirname(__FILE__) + '/dspacerest/repositories/dspace_repository'
require File.dirname(__FILE__) + '/dspacerest/repositories/item_repository'
require File.dirname(__FILE__) + '/dspacerest/strategies/uploads/curl_strategy'
require File.dirname(__FILE__) + '/dspacerest/strategies/uploads/rest_strategy'
require File.dirname(__FILE__) + '/dspacerest/builders/hash_builder'
require File.dirname(__FILE__) + '/dspacerest/builders/model_builder'
